tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "bat"
brew "gcc"
brew "direnv"
brew "diskus"
brew "docker"
brew "dust"
brew "exa"
brew "fd"
brew "gh"
brew "git"
brew "httpie"
brew "jq"
brew "k9s"
# brew "mecab"
# brew "mecab-ipadic"
# brew "youtube-dl"
# brew "mpv"
brew "neovim"
brew "nodebrew"
# brew "pandoc"
brew "poetry"
brew "procs"
brew "pyenv"
brew "starship"
brew "wget"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
cask "blackhole-16ch"
cask "blackhole-2ch"
# cask "blender"
# cask "chromedriver"
cask "deepl"
cask "font-hack-nerd-font"
cask "font-ricty-diminished"
cask "gimp"
cask "google-backup-and-sync"
cask "google-cloud-sdk"
# cask "google-japanese-ime"
# cask "miniforge"
# cask "obs"
# cask "orca"
cask "visual-studio-code"
cask "vlc"
# cask "wireshark"
