#!/bin/bash
if [ -f $(dirname $0)/../.config/git/config-user ]; then
    echo "Git already set up"
    read -p "Do you want to reset git? (y/n) " reset
    if [ "$reset" != "y" ]; then
        exit 0
    fi
fi

# Set up git
name=
email=

read -p "Enter your name: " name
read -p "Enter your email: " email

cat > $(dirname $0)/../.config/git/config-user <<EOF
[user]
    name = $name
    email = $email
EOF

echo "Git setup complete"
