[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
if = '!has("nvim")'
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
if = '!has("nvim")'
repo = 'roxma/nvim-yarp'

[[plugins]]
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  autocmd VimEnter * nested colorscheme iceberg
'''
repo = 'cocopon/iceberg.vim'
if = '!exists("g:vscode")'
[[plugins]]
hook_add = '''
let g:lightline = {
    \ 'colorscheme': 'iceberg',
    \ 'component_function': {
    \     'ale': 'ALEStatus'
    \ }
    \}
function! ALEStatus()
  return ALEGetStatusLine()
endfunction
'''
if = '!exists("g:vscode")'
repo = 'itchyny/lightline.vim'

[[plugins]]
hook_add = '''
let g:auto_save = 1  " enable AutoSave on Vim startup
let g:auto_save_in_insert_mode = 0  " do not save while in insert mode
let g:auto_save_silent = 1  " do not display the auto-save notification
'''
on_if = '!exists("g:vscode")'
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'Yggdroot/indentline'
if = '!exists("g:vscode")'
[[plugins]]
hook_add = '''
let g:mapleader = "\<Space>"
let g:EasyMotion_do_mapping = 0 " Disable default mappings
map <Leader> <Plug>(easymotion-s)
'''
if = 'exists("g:vscode")'
name = 'vim-easymotion-vscode'
repo = 'asvetliakov/vim-easymotion'

[[plugins]]
hook_add = '''
let g:mapleader = "\<Space>"
let g:EasyMotion_do_mapping = 0 " Disable default mappings
map <Leader> <Plug>(easymotion-s)
'''
if = '!exists("g:vscode")'
name = 'vim-easymotion'
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tpope/vim-commentary'
