[[plugins]]
if = '!exists("g:vscode")'
repo = 'Shougo/context_filetype.vim'

[[plugins]]
if = '!exists("g:vscode")'
on_ft = ['zsh', 'sh']
repo = 'zchee/deoplete-zsh'

[[plugins]]
depends = 'context_filetype.vim'
hook_source = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#jedi#python_path = '/Users/ryotaro/.pyenv/shims/python'

setlocal dictionary+=/usr/share/dict/words

inoremap <expr><C-h> deoplete#smart_close_popup()."<C-h>"
inoremap <expr><BS> deoplete#smart_close_popup()."<C-h>"
inoremap <expr><tab> pumvisible() ? "\<C-n>" :
    \ neosnippet#expandable_or_jumpable() ?
    \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"

call deoplete#custom#option({
    \ 'auto_complete': v:true,
    \ 'min_pattern_length': 1,
    \ 'auto_complete_delay': 0,
    \ 'auto_refresh_delay': 1,
    \ 'refresh_always': v:true,
    \ 'smart_case': v:true,
    \ 'camel_case': v:false,
    \ 'max_list': 10,
    \ })
"call deoplete#custom#source('dictionary', 'min_pattern_length', 4)
call deoplete#custom#option('sources', {
\ 'python': ['jedi',  'dictionary', 'file'],
\ 'vim': ['vim', 'buffer', 'dictionary', 'file'],
\ '_': ['file', 'dictionary'],
\})
" 一つ目の候補を選択状態にする
"set completeopt+=noinsert
" previw windowを消す(関数などの説明が書かれているウィンドウが出る)
set completeopt-=preview
call deoplete#enable()
'''
if = '!exists("g:vscode")'
on_event = 'InsertEnter'
repo = 'Shougo/deoplete.nvim'

[[plugins]]
if = '!exists("g:vscode")'
on_ft = 'python'
repo = 'deoplete-plugins/deoplete-jedi'

[[plugins]]
if = '!exists("g:vscode")'
on_event = 'InsertEnter'
repo = 'deoplete-plugins/deoplete-dictionary'

[[plugins]]
if = '!exists("g:vscode")'
on_ft = 'python'
repo = 'Vimjas/vim-python-pep8-indent'