name: Tests

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-op: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Ubuntu
        if: matrix.os ==  'ubuntu-latest'
        run: sudo apt-get install zsh
      - name: Install
        run: sudo ./install.sh --non-interactive --homebrew-install-python-tools --homebrew-install-font
      - name: Test
        run: ./test.sh
  test-docker:
    runs-op: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker compose up